name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Zainul342
          template: classic
          base: "" 
          config_timezone: Asia/Jakarta
          
          # 1. 3D Isometric Calendar (INI YANG PALING KEREN)
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
          # 2. Languages (Skill Proof)
          plugin_languages: yes
          plugin_languages_ignored: html, css, scss, shell, php
          plugin_languages_details: percentage
          plugin_languages_sections: most-used
          plugin_languages_limit: 5
