name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Zainul342
          template: classic
          base: "" # Mematikan header bawaan yang berantakan
          config_timezone: Asia/Jakarta
          
          # Hanya tampilkan bahasa pemrograman (Bukti Skill)
          plugin_languages: yes
          plugin_languages_ignored: html, css, scss, shell
          plugin_languages_details: percentage
          plugin_languages_sections: most-used
          plugin_languages_limit: 4
          
          # Tampilkan kontribusi secara ringkas
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
